- name: Demo on Variable
  hosts: all
  vars:
    URL: play.insta.com
  tasks: 
    - name: Print URL
      ansible.builtin.debug:
        msg: The value of the URL is {{ URL }}

    - name: Print URL
      ansible.builtin.debug:
        msg: The value of the URL is {{ URL }}
      vars: 
        URL: task.google.com

    - name: Print CLI_URL
      ansible.builtin.debug:
        msg: The value of the CLI_URL is {{ CLI_URL }}