- name: Demo on facts
  hosts: all
  tasks: 
    - name: Printing a fact
      ansible.builtin.debug:    
        msg: "{{ ansible_distribution }}"

    - name: Printing a macaddress
      ansible.builtin.debug:    
        msg: "{{ ansible_default_ip4.macaddress }}"

     