- name: Demo on shell
  hosts: all
  tasks:
    - name: Run Shell Command
      shell: uptime
      register: OUT


    - name: Printing the Output of uptime 
      ansible.builtin.debug:
        msg: "{{ OUT.stdout }}"